file,class,name,verdict,message,errors_in_stacktrace,errors_in_system_err,type,num,test_to_be_run,order
,,tests.test_place,Error,collection failure,"['    response = self.parent.error(', '/usr/local/lib/python3.10/urllib/request.py:563: in error', '/usr/local/lib/python3.10/urllib/request.py:643: in http_error_default', '    raise HTTPError(req.full_url, code, msg, hdrs, fp)', 'E   urllib.error.HTTPError: HTTP Error 403: Forbidden']",,,95,,same
,,tests.test_place,Error,collection failure,"['    response = self.parent.error(', '/usr/local/lib/python3.10/urllib/request.py:563: in error', '/usr/local/lib/python3.10/urllib/request.py:643: in http_error_default', '    raise HTTPError(req.full_url, code, msg, hdrs, fp)', 'E   urllib.error.HTTPError: HTTP Error 403: Forbidden']",,,191,,same
,,tests.test_place,Error,collection failure,"['    response = self.parent.error(', '/usr/local/lib/python3.10/urllib/request.py:563: in error', '/usr/local/lib/python3.10/urllib/request.py:643: in http_error_default', '    raise HTTPError(req.full_url, code, msg, hdrs, fp)', 'E   urllib.error.HTTPError: HTTP Error 403: Forbidden']",,,87,,same
,,tests.test_place,Error,collection failure,"['    response = self.parent.error(', '/usr/local/lib/python3.10/urllib/request.py:563: in error', '/usr/local/lib/python3.10/urllib/request.py:643: in http_error_default', '    raise HTTPError(req.full_url, code, msg, hdrs, fp)', 'E   urllib.error.HTTPError: HTTP Error 403: Forbidden']",,,139,,same
,,tests.test_place,Error,collection failure,"['    response = self.parent.error(', '/usr/local/lib/python3.10/urllib/request.py:563: in error', '/usr/local/lib/python3.10/urllib/request.py:643: in http_error_default', '    raise HTTPError(req.full_url, code, msg, hdrs, fp)', 'E   urllib.error.HTTPError: HTTP Error 403: Forbidden']",,,136,,same
,,tests.test_place,Error,collection failure,"['    response = self.parent.error(', '/usr/local/lib/python3.10/urllib/request.py:563: in error', '/usr/local/lib/python3.10/urllib/request.py:643: in http_error_default', '    raise HTTPError(req.full_url, code, msg, hdrs, fp)', 'E   urllib.error.HTTPError: HTTP Error 403: Forbidden']",,,44,,same
,,tests.test_place,Error,collection failure,"['    response = self.parent.error(', '/usr/local/lib/python3.10/urllib/request.py:563: in error', '/usr/local/lib/python3.10/urllib/request.py:643: in http_error_default', '    raise HTTPError(req.full_url, code, msg, hdrs, fp)', 'E   urllib.error.HTTPError: HTTP Error 403: Forbidden']",,,172,,same
,,tests.test_place,Error,collection failure,"['    response = self.parent.error(', '/usr/local/lib/python3.10/urllib/request.py:563: in error', '/usr/local/lib/python3.10/urllib/request.py:643: in http_error_default', '    raise HTTPError(req.full_url, code, msg, hdrs, fp)', 'E   urllib.error.HTTPError: HTTP Error 403: Forbidden']",,,20,,same
,,tests.test_place,Error,collection failure,"['    response = self.parent.error(', '/usr/local/lib/python3.10/urllib/request.py:563: in error', '/usr/local/lib/python3.10/urllib/request.py:643: in http_error_default', '    raise HTTPError(req.full_url, code, msg, hdrs, fp)', 'E   urllib.error.HTTPError: HTTP Error 403: Forbidden']",,,175,,same
,,tests.test_place,Error,collection failure,"['    response = self.parent.error(', '/usr/local/lib/python3.10/urllib/request.py:563: in error', '/usr/local/lib/python3.10/urllib/request.py:643: in http_error_default', '    raise HTTPError(req.full_url, code, msg, hdrs, fp)', 'E   urllib.error.HTTPError: HTTP Error 403: Forbidden']",,,41,,same
,,tests.test_place,Error,collection failure,"['    response = self.parent.error(', '/usr/local/lib/python3.10/urllib/request.py:563: in error', '/usr/local/lib/python3.10/urllib/request.py:643: in http_error_default', '    raise HTTPError(req.full_url, code, msg, hdrs, fp)', 'E   urllib.error.HTTPError: HTTP Error 403: Forbidden']",,,35,,same
,,tests.test_place,Error,collection failure,"['    response = self.parent.error(', '/usr/local/lib/python3.10/urllib/request.py:563: in error', '/usr/local/lib/python3.10/urllib/request.py:643: in http_error_default', '    raise HTTPError(req.full_url, code, msg, hdrs, fp)', 'E   urllib.error.HTTPError: HTTP Error 403: Forbidden']",,,61,,same
,,tests.test_place,Error,collection failure,"['    response = self.parent.error(', '/usr/local/lib/python3.10/urllib/request.py:563: in error', '/usr/local/lib/python3.10/urllib/request.py:643: in http_error_default', '    raise HTTPError(req.full_url, code, msg, hdrs, fp)', 'E   urllib.error.HTTPError: HTTP Error 403: Forbidden']",,,144,,same
,,tests.test_place,Error,collection failure,"['    response = self.parent.error(', '/usr/local/lib/python3.10/urllib/request.py:563: in error', '/usr/local/lib/python3.10/urllib/request.py:643: in http_error_default', '    raise HTTPError(req.full_url, code, msg, hdrs, fp)', 'E   urllib.error.HTTPError: HTTP Error 403: Forbidden']",,,180,,same
,,tests.test_place,Error,collection failure,"['    response = self.parent.error(', '/usr/local/lib/python3.10/urllib/request.py:563: in error', '/usr/local/lib/python3.10/urllib/request.py:643: in http_error_default', '    raise HTTPError(req.full_url, code, msg, hdrs, fp)', 'E   urllib.error.HTTPError: HTTP Error 403: Forbidden']",,,25,,same
,,tests.test_place,Error,collection failure,"['    response = self.parent.error(', '/usr/local/lib/python3.10/urllib/request.py:563: in error', '/usr/local/lib/python3.10/urllib/request.py:643: in http_error_default', '    raise HTTPError(req.full_url, code, msg, hdrs, fp)', 'E   urllib.error.HTTPError: HTTP Error 403: Forbidden']",,,9,,same
,,tests.test_place,Error,collection failure,"['    response = self.parent.error(', '/usr/local/lib/python3.10/urllib/request.py:563: in error', '/usr/local/lib/python3.10/urllib/request.py:643: in http_error_default', '    raise HTTPError(req.full_url, code, msg, hdrs, fp)', 'E   urllib.error.HTTPError: HTTP Error 403: Forbidden']",,,79,,same
,,tests.test_place,Error,collection failure,"['    response = self.parent.error(', '/usr/local/lib/python3.10/urllib/request.py:563: in error', '/usr/local/lib/python3.10/urllib/request.py:643: in http_error_default', '    raise HTTPError(req.full_url, code, msg, hdrs, fp)', 'E   urllib.error.HTTPError: HTTP Error 403: Forbidden']",,,52,,same
,,tests.test_place,Error,collection failure,"['    response = self.parent.error(', '/usr/local/lib/python3.10/urllib/request.py:563: in error', '/usr/local/lib/python3.10/urllib/request.py:643: in http_error_default', '    raise HTTPError(req.full_url, code, msg, hdrs, fp)', 'E   urllib.error.HTTPError: HTTP Error 403: Forbidden']",,,32,,same
,,tests.test_place,Error,collection failure,"['    response = self.parent.error(', '/usr/local/lib/python3.10/urllib/request.py:563: in error', '/usr/local/lib/python3.10/urllib/request.py:643: in http_error_default', '    raise HTTPError(req.full_url, code, msg, hdrs, fp)', 'E   urllib.error.HTTPError: HTTP Error 403: Forbidden']",,,179,,same
,,tests.test_place,Error,collection failure,"['    response = self.parent.error(', '/usr/local/lib/python3.10/urllib/request.py:563: in error', '/usr/local/lib/python3.10/urllib/request.py:643: in http_error_default', '    raise HTTPError(req.full_url, code, msg, hdrs, fp)', 'E   urllib.error.HTTPError: HTTP Error 403: Forbidden']",,,14,,same
,,tests.test_place,Error,collection failure,"['    response = self.parent.error(', '/usr/local/lib/python3.10/urllib/request.py:563: in error', '/usr/local/lib/python3.10/urllib/request.py:643: in http_error_default', '    raise HTTPError(req.full_url, code, msg, hdrs, fp)', 'E   urllib.error.HTTPError: HTTP Error 403: Forbidden']",,,66,,same
,,tests.test_place,Error,collection failure,"['    response = self.parent.error(', '/usr/local/lib/python3.10/urllib/request.py:563: in error', '/usr/local/lib/python3.10/urllib/request.py:643: in http_error_default', '    raise HTTPError(req.full_url, code, msg, hdrs, fp)', 'E   urllib.error.HTTPError: HTTP Error 403: Forbidden']",,,12,,same
,,tests.test_place,Error,collection failure,"['    response = self.parent.error(', '/usr/local/lib/python3.10/urllib/request.py:563: in error', '/usr/local/lib/python3.10/urllib/request.py:643: in http_error_default', '    raise HTTPError(req.full_url, code, msg, hdrs, fp)', 'E   urllib.error.HTTPError: HTTP Error 403: Forbidden']",,,31,,same
,,tests.test_place,Error,collection failure,"['    response = self.parent.error(', '/usr/local/lib/python3.10/urllib/request.py:563: in error', '/usr/local/lib/python3.10/urllib/request.py:643: in http_error_default', '    raise HTTPError(req.full_url, code, msg, hdrs, fp)', 'E   urllib.error.HTTPError: HTTP Error 403: Forbidden']",,,181,,same
,,tests.test_place,Error,collection failure,"['    response = self.parent.error(', '/usr/local/lib/python3.10/urllib/request.py:563: in error', '/usr/local/lib/python3.10/urllib/request.py:643: in http_error_default', '    raise HTTPError(req.full_url, code, msg, hdrs, fp)', 'E   urllib.error.HTTPError: HTTP Error 403: Forbidden']",,,77,,same
,,tests.test_place,Error,collection failure,"['    response = self.parent.error(', '/usr/local/lib/python3.10/urllib/request.py:563: in error', '/usr/local/lib/python3.10/urllib/request.py:643: in http_error_default', '    raise HTTPError(req.full_url, code, msg, hdrs, fp)', 'E   urllib.error.HTTPError: HTTP Error 403: Forbidden']",,,173,,same
,,tests.test_place,Error,collection failure,"['    response = self.parent.error(', '/usr/local/lib/python3.10/urllib/request.py:563: in error', '/usr/local/lib/python3.10/urllib/request.py:643: in http_error_default', '    raise HTTPError(req.full_url, code, msg, hdrs, fp)', 'E   urllib.error.HTTPError: HTTP Error 403: Forbidden']",,,43,,same
,,tests.test_place,Error,collection failure,"['    response = self.parent.error(', '/usr/local/lib/python3.10/urllib/request.py:563: in error', '/usr/local/lib/python3.10/urllib/request.py:643: in http_error_default', '    raise HTTPError(req.full_url, code, msg, hdrs, fp)', 'E   urllib.error.HTTPError: HTTP Error 403: Forbidden']",,,62,,same
,,tests.test_place,Error,collection failure,"['    response = self.parent.error(', '/usr/local/lib/python3.10/urllib/request.py:563: in error', '/usr/local/lib/python3.10/urllib/request.py:643: in http_error_default', '    raise HTTPError(req.full_url, code, msg, hdrs, fp)', 'E   urllib.error.HTTPError: HTTP Error 403: Forbidden']",,,27,,same
,,tests.test_place,Error,collection failure,"['    response = self.parent.error(', '/usr/local/lib/python3.10/urllib/request.py:563: in error', '/usr/local/lib/python3.10/urllib/request.py:643: in http_error_default', '    raise HTTPError(req.full_url, code, msg, hdrs, fp)', 'E   urllib.error.HTTPError: HTTP Error 403: Forbidden']",,,0,,same
,,tests.test_place,Error,collection failure,"['    response = self.parent.error(', '/usr/local/lib/python3.10/urllib/request.py:563: in error', '/usr/local/lib/python3.10/urllib/request.py:643: in http_error_default', '    raise HTTPError(req.full_url, code, msg, hdrs, fp)', 'E   urllib.error.HTTPError: HTTP Error 403: Forbidden']",,,19,,same
,,tests.test_place,Error,collection failure,"['    response = self.parent.error(', '/usr/local/lib/python3.10/urllib/request.py:563: in error', '/usr/local/lib/python3.10/urllib/request.py:643: in http_error_default', '    raise HTTPError(req.full_url, code, msg, hdrs, fp)', 'E   urllib.error.HTTPError: HTTP Error 403: Forbidden']",,,189,,same
,,tests.test_place,Error,collection failure,"['    response = self.parent.error(', '/usr/local/lib/python3.10/urllib/request.py:563: in error', '/usr/local/lib/python3.10/urllib/request.py:643: in http_error_default', '    raise HTTPError(req.full_url, code, msg, hdrs, fp)', 'E   urllib.error.HTTPError: HTTP Error 403: Forbidden']",,,92,,same
,,tests.test_place,Error,collection failure,"['    response = self.parent.error(', '/usr/local/lib/python3.10/urllib/request.py:563: in error', '/usr/local/lib/python3.10/urllib/request.py:643: in http_error_default', '    raise HTTPError(req.full_url, code, msg, hdrs, fp)', 'E   urllib.error.HTTPError: HTTP Error 403: Forbidden']",,,81,,same
,,tests.test_place,Error,collection failure,"['    response = self.parent.error(', '/usr/local/lib/python3.10/urllib/request.py:563: in error', '/usr/local/lib/python3.10/urllib/request.py:643: in http_error_default', '    raise HTTPError(req.full_url, code, msg, hdrs, fp)', 'E   urllib.error.HTTPError: HTTP Error 403: Forbidden']",,,142,,same
,,tests.test_place,Error,collection failure,"['    response = self.parent.error(', '/usr/local/lib/python3.10/urllib/request.py:563: in error', '/usr/local/lib/python3.10/urllib/request.py:643: in http_error_default', '    raise HTTPError(req.full_url, code, msg, hdrs, fp)', 'E   urllib.error.HTTPError: HTTP Error 403: Forbidden']",,,58,,same
,,tests.test_place,Error,collection failure,"['    response = self.parent.error(', '/usr/local/lib/python3.10/urllib/request.py:563: in error', '/usr/local/lib/python3.10/urllib/request.py:643: in http_error_default', '    raise HTTPError(req.full_url, code, msg, hdrs, fp)', 'E   urllib.error.HTTPError: HTTP Error 403: Forbidden']",,,83,,same
,,tests.test_place,Error,collection failure,"['    response = self.parent.error(', '/usr/local/lib/python3.10/urllib/request.py:563: in error', '/usr/local/lib/python3.10/urllib/request.py:643: in http_error_default', '    raise HTTPError(req.full_url, code, msg, hdrs, fp)', 'E   urllib.error.HTTPError: HTTP Error 403: Forbidden']",,,53,,same
,,tests.test_place,Error,collection failure,"['    response = self.parent.error(', '/usr/local/lib/python3.10/urllib/request.py:563: in error', '/usr/local/lib/python3.10/urllib/request.py:643: in http_error_default', '    raise HTTPError(req.full_url, code, msg, hdrs, fp)', 'E   urllib.error.HTTPError: HTTP Error 403: Forbidden']",,,94,,same
,,tests.test_place,Error,collection failure,"['    response = self.parent.error(', '/usr/local/lib/python3.10/urllib/request.py:563: in error', '/usr/local/lib/python3.10/urllib/request.py:643: in http_error_default', '    raise HTTPError(req.full_url, code, msg, hdrs, fp)', 'E   urllib.error.HTTPError: HTTP Error 403: Forbidden']",,,131,,same
,,tests.test_place,Error,collection failure,"['    response = self.parent.error(', '/usr/local/lib/python3.10/urllib/request.py:563: in error', '/usr/local/lib/python3.10/urllib/request.py:643: in http_error_default', '    raise HTTPError(req.full_url, code, msg, hdrs, fp)', 'E   urllib.error.HTTPError: HTTP Error 403: Forbidden']",,,7,,same
,,tests.test_place,Error,collection failure,"['    response = self.parent.error(', '/usr/local/lib/python3.10/urllib/request.py:563: in error', '/usr/local/lib/python3.10/urllib/request.py:643: in http_error_default', '    raise HTTPError(req.full_url, code, msg, hdrs, fp)', 'E   urllib.error.HTTPError: HTTP Error 403: Forbidden']",,,29,,same
,,tests.test_place,Error,collection failure,"['    response = self.parent.error(', '/usr/local/lib/python3.10/urllib/request.py:563: in error', '/usr/local/lib/python3.10/urllib/request.py:643: in http_error_default', '    raise HTTPError(req.full_url, code, msg, hdrs, fp)', 'E   urllib.error.HTTPError: HTTP Error 403: Forbidden']",,,111,,same
,,tests.test_place,Error,collection failure,"['    response = self.parent.error(', '/usr/local/lib/python3.10/urllib/request.py:563: in error', '/usr/local/lib/python3.10/urllib/request.py:643: in http_error_default', '    raise HTTPError(req.full_url, code, msg, hdrs, fp)', 'E   urllib.error.HTTPError: HTTP Error 403: Forbidden']",,,135,,same
,,tests.test_place,Error,collection failure,"['    response = self.parent.error(', '/usr/local/lib/python3.10/urllib/request.py:563: in error', '/usr/local/lib/python3.10/urllib/request.py:643: in http_error_default', '    raise HTTPError(req.full_url, code, msg, hdrs, fp)', 'E   urllib.error.HTTPError: HTTP Error 403: Forbidden']",,,45,,same
,,tests.test_place,Error,collection failure,"['    response = self.parent.error(', '/usr/local/lib/python3.10/urllib/request.py:563: in error', '/usr/local/lib/python3.10/urllib/request.py:643: in http_error_default', '    raise HTTPError(req.full_url, code, msg, hdrs, fp)', 'E   urllib.error.HTTPError: HTTP Error 403: Forbidden']",,,105,,same
,,tests.test_place,Error,collection failure,"['    response = self.parent.error(', '/usr/local/lib/python3.10/urllib/request.py:563: in error', '/usr/local/lib/python3.10/urllib/request.py:643: in http_error_default', '    raise HTTPError(req.full_url, code, msg, hdrs, fp)', 'E   urllib.error.HTTPError: HTTP Error 403: Forbidden']",,,55,,same
,,tests.test_place,Error,collection failure,"['    response = self.parent.error(', '/usr/local/lib/python3.10/urllib/request.py:563: in error', '/usr/local/lib/python3.10/urllib/request.py:643: in http_error_default', '    raise HTTPError(req.full_url, code, msg, hdrs, fp)', 'E   urllib.error.HTTPError: HTTP Error 403: Forbidden']",,,162,,same
,,tests.test_place,Error,collection failure,"['    response = self.parent.error(', '/usr/local/lib/python3.10/urllib/request.py:563: in error', '/usr/local/lib/python3.10/urllib/request.py:643: in http_error_default', '    raise HTTPError(req.full_url, code, msg, hdrs, fp)', 'E   urllib.error.HTTPError: HTTP Error 403: Forbidden']",,,97,,same
,,tests.test_place,Error,collection failure,"['    response = self.parent.error(', '/usr/local/lib/python3.10/urllib/request.py:563: in error', '/usr/local/lib/python3.10/urllib/request.py:643: in http_error_default', '    raise HTTPError(req.full_url, code, msg, hdrs, fp)', 'E   urllib.error.HTTPError: HTTP Error 403: Forbidden']",,,177,,same
,,tests.test_place,Error,collection failure,"['    response = self.parent.error(', '/usr/local/lib/python3.10/urllib/request.py:563: in error', '/usr/local/lib/python3.10/urllib/request.py:643: in http_error_default', '    raise HTTPError(req.full_url, code, msg, hdrs, fp)', 'E   urllib.error.HTTPError: HTTP Error 403: Forbidden']",,,54,,same
,,tests.test_place,Error,collection failure,"['    response = self.parent.error(', '/usr/local/lib/python3.10/urllib/request.py:563: in error', '/usr/local/lib/python3.10/urllib/request.py:643: in http_error_default', '    raise HTTPError(req.full_url, code, msg, hdrs, fp)', 'E   urllib.error.HTTPError: HTTP Error 403: Forbidden']",,,141,,same
,,tests.test_place,Error,collection failure,"['    response = self.parent.error(', '/usr/local/lib/python3.10/urllib/request.py:563: in error', '/usr/local/lib/python3.10/urllib/request.py:643: in http_error_default', '    raise HTTPError(req.full_url, code, msg, hdrs, fp)', 'E   urllib.error.HTTPError: HTTP Error 403: Forbidden']",,,63,,same
,,tests.test_place,Error,collection failure,"['    response = self.parent.error(', '/usr/local/lib/python3.10/urllib/request.py:563: in error', '/usr/local/lib/python3.10/urllib/request.py:643: in http_error_default', '    raise HTTPError(req.full_url, code, msg, hdrs, fp)', 'E   urllib.error.HTTPError: HTTP Error 403: Forbidden']",,,120,,same
,,tests.test_place,Error,collection failure,"['    response = self.parent.error(', '/usr/local/lib/python3.10/urllib/request.py:563: in error', '/usr/local/lib/python3.10/urllib/request.py:643: in http_error_default', '    raise HTTPError(req.full_url, code, msg, hdrs, fp)', 'E   urllib.error.HTTPError: HTTP Error 403: Forbidden']",,,107,,same
,,tests.test_place,Error,collection failure,"['    response = self.parent.error(', '/usr/local/lib/python3.10/urllib/request.py:563: in error', '/usr/local/lib/python3.10/urllib/request.py:643: in http_error_default', '    raise HTTPError(req.full_url, code, msg, hdrs, fp)', 'E   urllib.error.HTTPError: HTTP Error 403: Forbidden']",,,84,,same
,,tests.test_place,Error,collection failure,"['    response = self.parent.error(', '/usr/local/lib/python3.10/urllib/request.py:563: in error', '/usr/local/lib/python3.10/urllib/request.py:643: in http_error_default', '    raise HTTPError(req.full_url, code, msg, hdrs, fp)', 'E   urllib.error.HTTPError: HTTP Error 403: Forbidden']",,,93,,same
,,tests.test_place,Error,collection failure,"['    response = self.parent.error(', '/usr/local/lib/python3.10/urllib/request.py:563: in error', '/usr/local/lib/python3.10/urllib/request.py:643: in http_error_default', '    raise HTTPError(req.full_url, code, msg, hdrs, fp)', 'E   urllib.error.HTTPError: HTTP Error 403: Forbidden']",,,102,,same
,,tests.test_place,Error,collection failure,"['    response = self.parent.error(', '/usr/local/lib/python3.10/urllib/request.py:563: in error', '/usr/local/lib/python3.10/urllib/request.py:643: in http_error_default', '    raise HTTPError(req.full_url, code, msg, hdrs, fp)', 'E   urllib.error.HTTPError: HTTP Error 403: Forbidden']",,,154,,same
,,tests.test_place,Error,collection failure,"['    response = self.parent.error(', '/usr/local/lib/python3.10/urllib/request.py:563: in error', '/usr/local/lib/python3.10/urllib/request.py:643: in http_error_default', '    raise HTTPError(req.full_url, code, msg, hdrs, fp)', 'E   urllib.error.HTTPError: HTTP Error 403: Forbidden']",,,110,,same
,,tests.test_place,Error,collection failure,"['    response = self.parent.error(', '/usr/local/lib/python3.10/urllib/request.py:563: in error', '/usr/local/lib/python3.10/urllib/request.py:643: in http_error_default', '    raise HTTPError(req.full_url, code, msg, hdrs, fp)', 'E   urllib.error.HTTPError: HTTP Error 403: Forbidden']",,,16,,same
,,tests.test_place,Error,collection failure,"['    response = self.parent.error(', '/usr/local/lib/python3.10/urllib/request.py:563: in error', '/usr/local/lib/python3.10/urllib/request.py:643: in http_error_default', '    raise HTTPError(req.full_url, code, msg, hdrs, fp)', 'E   urllib.error.HTTPError: HTTP Error 403: Forbidden']",,,160,,same
,,tests.test_place,Error,collection failure,"['    response = self.parent.error(', '/usr/local/lib/python3.10/urllib/request.py:563: in error', '/usr/local/lib/python3.10/urllib/request.py:643: in http_error_default', '    raise HTTPError(req.full_url, code, msg, hdrs, fp)', 'E   urllib.error.HTTPError: HTTP Error 403: Forbidden']",,,195,,same
,,tests.test_place,Error,collection failure,"['    response = self.parent.error(', '/usr/local/lib/python3.10/urllib/request.py:563: in error', '/usr/local/lib/python3.10/urllib/request.py:643: in http_error_default', '    raise HTTPError(req.full_url, code, msg, hdrs, fp)', 'E   urllib.error.HTTPError: HTTP Error 403: Forbidden']",,,184,,same
,,tests.test_place,Error,collection failure,"['    response = self.parent.error(', '/usr/local/lib/python3.10/urllib/request.py:563: in error', '/usr/local/lib/python3.10/urllib/request.py:643: in http_error_default', '    raise HTTPError(req.full_url, code, msg, hdrs, fp)', 'E   urllib.error.HTTPError: HTTP Error 403: Forbidden']",,,59,,same
,,tests.test_place,Error,collection failure,"['    response = self.parent.error(', '/usr/local/lib/python3.10/urllib/request.py:563: in error', '/usr/local/lib/python3.10/urllib/request.py:643: in http_error_default', '    raise HTTPError(req.full_url, code, msg, hdrs, fp)', 'E   urllib.error.HTTPError: HTTP Error 403: Forbidden']",,,73,,same
,,tests.test_place,Error,collection failure,"['    response = self.parent.error(', '/usr/local/lib/python3.10/urllib/request.py:563: in error', '/usr/local/lib/python3.10/urllib/request.py:643: in http_error_default', '    raise HTTPError(req.full_url, code, msg, hdrs, fp)', 'E   urllib.error.HTTPError: HTTP Error 403: Forbidden']",,,122,,same
,,tests.test_place,Error,collection failure,"['    response = self.parent.error(', '/usr/local/lib/python3.10/urllib/request.py:563: in error', '/usr/local/lib/python3.10/urllib/request.py:643: in http_error_default', '    raise HTTPError(req.full_url, code, msg, hdrs, fp)', 'E   urllib.error.HTTPError: HTTP Error 403: Forbidden']",,,133,,same
,,tests.test_place,Error,collection failure,"['    response = self.parent.error(', '/usr/local/lib/python3.10/urllib/request.py:563: in error', '/usr/local/lib/python3.10/urllib/request.py:643: in http_error_default', '    raise HTTPError(req.full_url, code, msg, hdrs, fp)', 'E   urllib.error.HTTPError: HTTP Error 403: Forbidden']",,,129,,same
,,tests.test_place,Error,collection failure,"['    response = self.parent.error(', '/usr/local/lib/python3.10/urllib/request.py:563: in error', '/usr/local/lib/python3.10/urllib/request.py:643: in http_error_default', '    raise HTTPError(req.full_url, code, msg, hdrs, fp)', 'E   urllib.error.HTTPError: HTTP Error 403: Forbidden']",,,127,,same
,,tests.test_place,Error,collection failure,"['    response = self.parent.error(', '/usr/local/lib/python3.10/urllib/request.py:563: in error', '/usr/local/lib/python3.10/urllib/request.py:643: in http_error_default', '    raise HTTPError(req.full_url, code, msg, hdrs, fp)', 'E   urllib.error.HTTPError: HTTP Error 403: Forbidden']",,,101,,same
,,tests.test_place,Error,collection failure,"['    response = self.parent.error(', '/usr/local/lib/python3.10/urllib/request.py:563: in error', '/usr/local/lib/python3.10/urllib/request.py:643: in http_error_default', '    raise HTTPError(req.full_url, code, msg, hdrs, fp)', 'E   urllib.error.HTTPError: HTTP Error 403: Forbidden']",,,4,,same
,,tests.test_place,Error,collection failure,"['    response = self.parent.error(', '/usr/local/lib/python3.10/urllib/request.py:563: in error', '/usr/local/lib/python3.10/urllib/request.py:643: in http_error_default', '    raise HTTPError(req.full_url, code, msg, hdrs, fp)', 'E   urllib.error.HTTPError: HTTP Error 403: Forbidden']",,,117,,same
,,tests.test_place,Error,collection failure,"['    response = self.parent.error(', '/usr/local/lib/python3.10/urllib/request.py:563: in error', '/usr/local/lib/python3.10/urllib/request.py:643: in http_error_default', '    raise HTTPError(req.full_url, code, msg, hdrs, fp)', 'E   urllib.error.HTTPError: HTTP Error 403: Forbidden']",,,109,,same
,,tests.test_place,Error,collection failure,"['    response = self.parent.error(', '/usr/local/lib/python3.10/urllib/request.py:563: in error', '/usr/local/lib/python3.10/urllib/request.py:643: in http_error_default', '    raise HTTPError(req.full_url, code, msg, hdrs, fp)', 'E   urllib.error.HTTPError: HTTP Error 403: Forbidden']",,,151,,same
,,tests.test_place,Error,collection failure,"['    response = self.parent.error(', '/usr/local/lib/python3.10/urllib/request.py:563: in error', '/usr/local/lib/python3.10/urllib/request.py:643: in http_error_default', '    raise HTTPError(req.full_url, code, msg, hdrs, fp)', 'E   urllib.error.HTTPError: HTTP Error 403: Forbidden']",,,146,,same
,,tests.test_place,Error,collection failure,"['    response = self.parent.error(', '/usr/local/lib/python3.10/urllib/request.py:563: in error', '/usr/local/lib/python3.10/urllib/request.py:643: in http_error_default', '    raise HTTPError(req.full_url, code, msg, hdrs, fp)', 'E   urllib.error.HTTPError: HTTP Error 403: Forbidden']",,,23,,same
,,tests.test_place,Error,collection failure,"['    response = self.parent.error(', '/usr/local/lib/python3.10/urllib/request.py:563: in error', '/usr/local/lib/python3.10/urllib/request.py:643: in http_error_default', '    raise HTTPError(req.full_url, code, msg, hdrs, fp)', 'E   urllib.error.HTTPError: HTTP Error 403: Forbidden']",,,68,,same
,,tests.test_place,Error,collection failure,"['    response = self.parent.error(', '/usr/local/lib/python3.10/urllib/request.py:563: in error', '/usr/local/lib/python3.10/urllib/request.py:643: in http_error_default', '    raise HTTPError(req.full_url, code, msg, hdrs, fp)', 'E   urllib.error.HTTPError: HTTP Error 403: Forbidden']",,,3,,same
,,tests.test_place,Error,collection failure,"['    response = self.parent.error(', '/usr/local/lib/python3.10/urllib/request.py:563: in error', '/usr/local/lib/python3.10/urllib/request.py:643: in http_error_default', '    raise HTTPError(req.full_url, code, msg, hdrs, fp)', 'E   urllib.error.HTTPError: HTTP Error 403: Forbidden']",,,76,,same
,,tests.test_place,Error,collection failure,"['    response = self.parent.error(', '/usr/local/lib/python3.10/urllib/request.py:563: in error', '/usr/local/lib/python3.10/urllib/request.py:643: in http_error_default', '    raise HTTPError(req.full_url, code, msg, hdrs, fp)', 'E   urllib.error.HTTPError: HTTP Error 403: Forbidden']",,,98,,same
,,tests.test_place,Error,collection failure,"['    response = self.parent.error(', '/usr/local/lib/python3.10/urllib/request.py:563: in error', '/usr/local/lib/python3.10/urllib/request.py:643: in http_error_default', '    raise HTTPError(req.full_url, code, msg, hdrs, fp)', 'E   urllib.error.HTTPError: HTTP Error 403: Forbidden']",,,163,,same
,,tests.test_place,Error,collection failure,"['    response = self.parent.error(', '/usr/local/lib/python3.10/urllib/request.py:563: in error', '/usr/local/lib/python3.10/urllib/request.py:643: in http_error_default', '    raise HTTPError(req.full_url, code, msg, hdrs, fp)', 'E   urllib.error.HTTPError: HTTP Error 403: Forbidden']",,,134,,same
,,tests.test_place,Error,collection failure,"['    response = self.parent.error(', '/usr/local/lib/python3.10/urllib/request.py:563: in error', '/usr/local/lib/python3.10/urllib/request.py:643: in http_error_default', '    raise HTTPError(req.full_url, code, msg, hdrs, fp)', 'E   urllib.error.HTTPError: HTTP Error 403: Forbidden']",,,156,,same
,,tests.test_place,Error,collection failure,"['    response = self.parent.error(', '/usr/local/lib/python3.10/urllib/request.py:563: in error', '/usr/local/lib/python3.10/urllib/request.py:643: in http_error_default', '    raise HTTPError(req.full_url, code, msg, hdrs, fp)', 'E   urllib.error.HTTPError: HTTP Error 403: Forbidden']",,,86,,same
,,tests.test_place,Error,collection failure,"['    response = self.parent.error(', '/usr/local/lib/python3.10/urllib/request.py:563: in error', '/usr/local/lib/python3.10/urllib/request.py:643: in http_error_default', '    raise HTTPError(req.full_url, code, msg, hdrs, fp)', 'E   urllib.error.HTTPError: HTTP Error 403: Forbidden']",,,125,,same
,,tests.test_place,Error,collection failure,"['    response = self.parent.error(', '/usr/local/lib/python3.10/urllib/request.py:563: in error', '/usr/local/lib/python3.10/urllib/request.py:643: in http_error_default', '    raise HTTPError(req.full_url, code, msg, hdrs, fp)', 'E   urllib.error.HTTPError: HTTP Error 403: Forbidden']",,,57,,same
,,tests.test_place,Error,collection failure,"['    response = self.parent.error(', '/usr/local/lib/python3.10/urllib/request.py:563: in error', '/usr/local/lib/python3.10/urllib/request.py:643: in http_error_default', '    raise HTTPError(req.full_url, code, msg, hdrs, fp)', 'E   urllib.error.HTTPError: HTTP Error 403: Forbidden']",,,13,,same
,,tests.test_place,Error,collection failure,"['    response = self.parent.error(', '/usr/local/lib/python3.10/urllib/request.py:563: in error', '/usr/local/lib/python3.10/urllib/request.py:643: in http_error_default', '    raise HTTPError(req.full_url, code, msg, hdrs, fp)', 'E   urllib.error.HTTPError: HTTP Error 403: Forbidden']",,,176,,same
,,tests.test_place,Error,collection failure,"['    response = self.parent.error(', '/usr/local/lib/python3.10/urllib/request.py:563: in error', '/usr/local/lib/python3.10/urllib/request.py:643: in http_error_default', '    raise HTTPError(req.full_url, code, msg, hdrs, fp)', 'E   urllib.error.HTTPError: HTTP Error 403: Forbidden']",,,145,,same
,,tests.test_place,Error,collection failure,"['    response = self.parent.error(', '/usr/local/lib/python3.10/urllib/request.py:563: in error', '/usr/local/lib/python3.10/urllib/request.py:643: in http_error_default', '    raise HTTPError(req.full_url, code, msg, hdrs, fp)', 'E   urllib.error.HTTPError: HTTP Error 403: Forbidden']",,,2,,same
,,tests.test_place,Error,collection failure,"['    response = self.parent.error(', '/usr/local/lib/python3.10/urllib/request.py:563: in error', '/usr/local/lib/python3.10/urllib/request.py:643: in http_error_default', '    raise HTTPError(req.full_url, code, msg, hdrs, fp)', 'E   urllib.error.HTTPError: HTTP Error 403: Forbidden']",,,149,,same
,,tests.test_place,Error,collection failure,"['    response = self.parent.error(', '/usr/local/lib/python3.10/urllib/request.py:563: in error', '/usr/local/lib/python3.10/urllib/request.py:643: in http_error_default', '    raise HTTPError(req.full_url, code, msg, hdrs, fp)', 'E   urllib.error.HTTPError: HTTP Error 403: Forbidden']",,,47,,same
,,tests.test_place,Error,collection failure,"['    response = self.parent.error(', '/usr/local/lib/python3.10/urllib/request.py:563: in error', '/usr/local/lib/python3.10/urllib/request.py:643: in http_error_default', '    raise HTTPError(req.full_url, code, msg, hdrs, fp)', 'E   urllib.error.HTTPError: HTTP Error 403: Forbidden']",,,67,,same
,,tests.test_place,Error,collection failure,"['    response = self.parent.error(', '/usr/local/lib/python3.10/urllib/request.py:563: in error', '/usr/local/lib/python3.10/urllib/request.py:643: in http_error_default', '    raise HTTPError(req.full_url, code, msg, hdrs, fp)', 'E   urllib.error.HTTPError: HTTP Error 403: Forbidden']",,,188,,same
,,tests.test_place,Error,collection failure,"['    response = self.parent.error(', '/usr/local/lib/python3.10/urllib/request.py:563: in error', '/usr/local/lib/python3.10/urllib/request.py:643: in http_error_default', '    raise HTTPError(req.full_url, code, msg, hdrs, fp)', 'E   urllib.error.HTTPError: HTTP Error 403: Forbidden']",,,10,,same
,,tests.test_place,Error,collection failure,"['    response = self.parent.error(', '/usr/local/lib/python3.10/urllib/request.py:563: in error', '/usr/local/lib/python3.10/urllib/request.py:643: in http_error_default', '    raise HTTPError(req.full_url, code, msg, hdrs, fp)', 'E   urllib.error.HTTPError: HTTP Error 403: Forbidden']",,,108,,same
,,tests.test_place,Error,collection failure,"['    response = self.parent.error(', '/usr/local/lib/python3.10/urllib/request.py:563: in error', '/usr/local/lib/python3.10/urllib/request.py:643: in http_error_default', '    raise HTTPError(req.full_url, code, msg, hdrs, fp)', 'E   urllib.error.HTTPError: HTTP Error 403: Forbidden']",,,80,,same
,,tests.test_place,Error,collection failure,"['    response = self.parent.error(', '/usr/local/lib/python3.10/urllib/request.py:563: in error', '/usr/local/lib/python3.10/urllib/request.py:643: in http_error_default', '    raise HTTPError(req.full_url, code, msg, hdrs, fp)', 'E   urllib.error.HTTPError: HTTP Error 403: Forbidden']",,,8,,same
,,tests.test_place,Error,collection failure,"['    response = self.parent.error(', '/usr/local/lib/python3.10/urllib/request.py:563: in error', '/usr/local/lib/python3.10/urllib/request.py:643: in http_error_default', '    raise HTTPError(req.full_url, code, msg, hdrs, fp)', 'E   urllib.error.HTTPError: HTTP Error 403: Forbidden']",,,49,,same
,,tests.test_place,Error,collection failure,"['    response = self.parent.error(', '/usr/local/lib/python3.10/urllib/request.py:563: in error', '/usr/local/lib/python3.10/urllib/request.py:643: in http_error_default', '    raise HTTPError(req.full_url, code, msg, hdrs, fp)', 'E   urllib.error.HTTPError: HTTP Error 403: Forbidden']",,,170,,same
,,tests.test_place,Error,collection failure,"['    response = self.parent.error(', '/usr/local/lib/python3.10/urllib/request.py:563: in error', '/usr/local/lib/python3.10/urllib/request.py:643: in http_error_default', '    raise HTTPError(req.full_url, code, msg, hdrs, fp)', 'E   urllib.error.HTTPError: HTTP Error 403: Forbidden']",,,51,,same
,,tests.test_place,Error,collection failure,"['    response = self.parent.error(', '/usr/local/lib/python3.10/urllib/request.py:563: in error', '/usr/local/lib/python3.10/urllib/request.py:643: in http_error_default', '    raise HTTPError(req.full_url, code, msg, hdrs, fp)', 'E   urllib.error.HTTPError: HTTP Error 403: Forbidden']",,,147,,same
,,tests.test_place,Error,collection failure,"['    response = self.parent.error(', '/usr/local/lib/python3.10/urllib/request.py:563: in error', '/usr/local/lib/python3.10/urllib/request.py:643: in http_error_default', '    raise HTTPError(req.full_url, code, msg, hdrs, fp)', 'E   urllib.error.HTTPError: HTTP Error 403: Forbidden']",,,38,,same
,,tests.test_place,Error,collection failure,"['    response = self.parent.error(', '/usr/local/lib/python3.10/urllib/request.py:563: in error', '/usr/local/lib/python3.10/urllib/request.py:643: in http_error_default', '    raise HTTPError(req.full_url, code, msg, hdrs, fp)', 'E   urllib.error.HTTPError: HTTP Error 403: Forbidden']",,,11,,same
,,tests.test_place,Error,collection failure,"['    response = self.parent.error(', '/usr/local/lib/python3.10/urllib/request.py:563: in error', '/usr/local/lib/python3.10/urllib/request.py:643: in http_error_default', '    raise HTTPError(req.full_url, code, msg, hdrs, fp)', 'E   urllib.error.HTTPError: HTTP Error 403: Forbidden']",,,128,,same
,,tests.test_place,Error,collection failure,"['    response = self.parent.error(', '/usr/local/lib/python3.10/urllib/request.py:563: in error', '/usr/local/lib/python3.10/urllib/request.py:643: in http_error_default', '    raise HTTPError(req.full_url, code, msg, hdrs, fp)', 'E   urllib.error.HTTPError: HTTP Error 403: Forbidden']",,,17,,same
,,tests.test_place,Error,collection failure,"['    response = self.parent.error(', '/usr/local/lib/python3.10/urllib/request.py:563: in error', '/usr/local/lib/python3.10/urllib/request.py:643: in http_error_default', '    raise HTTPError(req.full_url, code, msg, hdrs, fp)', 'E   urllib.error.HTTPError: HTTP Error 403: Forbidden']",,,121,,same
,,tests.test_place,Error,collection failure,"['    response = self.parent.error(', '/usr/local/lib/python3.10/urllib/request.py:563: in error', '/usr/local/lib/python3.10/urllib/request.py:643: in http_error_default', '    raise HTTPError(req.full_url, code, msg, hdrs, fp)', 'E   urllib.error.HTTPError: HTTP Error 403: Forbidden']",,,148,,same
,,tests.test_place,Error,collection failure,"['    response = self.parent.error(', '/usr/local/lib/python3.10/urllib/request.py:563: in error', '/usr/local/lib/python3.10/urllib/request.py:643: in http_error_default', '    raise HTTPError(req.full_url, code, msg, hdrs, fp)', 'E   urllib.error.HTTPError: HTTP Error 403: Forbidden']",,,71,,same
,,tests.test_place,Error,collection failure,"['    response = self.parent.error(', '/usr/local/lib/python3.10/urllib/request.py:563: in error', '/usr/local/lib/python3.10/urllib/request.py:643: in http_error_default', '    raise HTTPError(req.full_url, code, msg, hdrs, fp)', 'E   urllib.error.HTTPError: HTTP Error 403: Forbidden']",,,28,,same
,,tests.test_place,Error,collection failure,"['    response = self.parent.error(', '/usr/local/lib/python3.10/urllib/request.py:563: in error', '/usr/local/lib/python3.10/urllib/request.py:643: in http_error_default', '    raise HTTPError(req.full_url, code, msg, hdrs, fp)', 'E   urllib.error.HTTPError: HTTP Error 403: Forbidden']",,,22,,same
,,tests.test_place,Error,collection failure,"['    response = self.parent.error(', '/usr/local/lib/python3.10/urllib/request.py:563: in error', '/usr/local/lib/python3.10/urllib/request.py:643: in http_error_default', '    raise HTTPError(req.full_url, code, msg, hdrs, fp)', 'E   urllib.error.HTTPError: HTTP Error 403: Forbidden']",,,50,,same
,,tests.test_place,Error,collection failure,"['    response = self.parent.error(', '/usr/local/lib/python3.10/urllib/request.py:563: in error', '/usr/local/lib/python3.10/urllib/request.py:643: in http_error_default', '    raise HTTPError(req.full_url, code, msg, hdrs, fp)', 'E   urllib.error.HTTPError: HTTP Error 403: Forbidden']",,,5,,same
,,tests.test_place,Error,collection failure,"['    response = self.parent.error(', '/usr/local/lib/python3.10/urllib/request.py:563: in error', '/usr/local/lib/python3.10/urllib/request.py:643: in http_error_default', '    raise HTTPError(req.full_url, code, msg, hdrs, fp)', 'E   urllib.error.HTTPError: HTTP Error 403: Forbidden']",,,178,,same
,,tests.test_place,Error,collection failure,"['    response = self.parent.error(', '/usr/local/lib/python3.10/urllib/request.py:563: in error', '/usr/local/lib/python3.10/urllib/request.py:643: in http_error_default', '    raise HTTPError(req.full_url, code, msg, hdrs, fp)', 'E   urllib.error.HTTPError: HTTP Error 403: Forbidden']",,,165,,same
,,tests.test_place,Error,collection failure,"['    response = self.parent.error(', '/usr/local/lib/python3.10/urllib/request.py:563: in error', '/usr/local/lib/python3.10/urllib/request.py:643: in http_error_default', '    raise HTTPError(req.full_url, code, msg, hdrs, fp)', 'E   urllib.error.HTTPError: HTTP Error 403: Forbidden']",,,116,,same
,,tests.test_place,Error,collection failure,"['    response = self.parent.error(', '/usr/local/lib/python3.10/urllib/request.py:563: in error', '/usr/local/lib/python3.10/urllib/request.py:643: in http_error_default', '    raise HTTPError(req.full_url, code, msg, hdrs, fp)', 'E   urllib.error.HTTPError: HTTP Error 403: Forbidden']",,,104,,same
,,tests.test_place,Error,collection failure,"['    response = self.parent.error(', '/usr/local/lib/python3.10/urllib/request.py:563: in error', '/usr/local/lib/python3.10/urllib/request.py:643: in http_error_default', '    raise HTTPError(req.full_url, code, msg, hdrs, fp)', 'E   urllib.error.HTTPError: HTTP Error 403: Forbidden']",,,153,,same
,,tests.test_place,Error,collection failure,"['    response = self.parent.error(', '/usr/local/lib/python3.10/urllib/request.py:563: in error', '/usr/local/lib/python3.10/urllib/request.py:643: in http_error_default', '    raise HTTPError(req.full_url, code, msg, hdrs, fp)', 'E   urllib.error.HTTPError: HTTP Error 403: Forbidden']",,,100,,same
,,tests.test_place,Error,collection failure,"['    response = self.parent.error(', '/usr/local/lib/python3.10/urllib/request.py:563: in error', '/usr/local/lib/python3.10/urllib/request.py:643: in http_error_default', '    raise HTTPError(req.full_url, code, msg, hdrs, fp)', 'E   urllib.error.HTTPError: HTTP Error 403: Forbidden']",,,118,,same
,,tests.test_place,Error,collection failure,"['    response = self.parent.error(', '/usr/local/lib/python3.10/urllib/request.py:563: in error', '/usr/local/lib/python3.10/urllib/request.py:643: in http_error_default', '    raise HTTPError(req.full_url, code, msg, hdrs, fp)', 'E   urllib.error.HTTPError: HTTP Error 403: Forbidden']",,,174,,same
,,tests.test_place,Error,collection failure,"['    response = self.parent.error(', '/usr/local/lib/python3.10/urllib/request.py:563: in error', '/usr/local/lib/python3.10/urllib/request.py:643: in http_error_default', '    raise HTTPError(req.full_url, code, msg, hdrs, fp)', 'E   urllib.error.HTTPError: HTTP Error 403: Forbidden']",,,96,,same
,,tests.test_place,Error,collection failure,"['    response = self.parent.error(', '/usr/local/lib/python3.10/urllib/request.py:563: in error', '/usr/local/lib/python3.10/urllib/request.py:643: in http_error_default', '    raise HTTPError(req.full_url, code, msg, hdrs, fp)', 'E   urllib.error.HTTPError: HTTP Error 403: Forbidden']",,,190,,same
,,tests.test_place,Error,collection failure,"['    response = self.parent.error(', '/usr/local/lib/python3.10/urllib/request.py:563: in error', '/usr/local/lib/python3.10/urllib/request.py:643: in http_error_default', '    raise HTTPError(req.full_url, code, msg, hdrs, fp)', 'E   urllib.error.HTTPError: HTTP Error 403: Forbidden']",,,155,,same
,,tests.test_place,Error,collection failure,"['    response = self.parent.error(', '/usr/local/lib/python3.10/urllib/request.py:563: in error', '/usr/local/lib/python3.10/urllib/request.py:643: in http_error_default', '    raise HTTPError(req.full_url, code, msg, hdrs, fp)', 'E   urllib.error.HTTPError: HTTP Error 403: Forbidden']",,,140,,same
,,tests.test_place,Error,collection failure,"['    response = self.parent.error(', '/usr/local/lib/python3.10/urllib/request.py:563: in error', '/usr/local/lib/python3.10/urllib/request.py:643: in http_error_default', '    raise HTTPError(req.full_url, code, msg, hdrs, fp)', 'E   urllib.error.HTTPError: HTTP Error 403: Forbidden']",,,78,,same
,,tests.test_place,Error,collection failure,"['    response = self.parent.error(', '/usr/local/lib/python3.10/urllib/request.py:563: in error', '/usr/local/lib/python3.10/urllib/request.py:643: in http_error_default', '    raise HTTPError(req.full_url, code, msg, hdrs, fp)', 'E   urllib.error.HTTPError: HTTP Error 403: Forbidden']",,,103,,same
,,tests.test_place,Error,collection failure,"['    response = self.parent.error(', '/usr/local/lib/python3.10/urllib/request.py:563: in error', '/usr/local/lib/python3.10/urllib/request.py:643: in http_error_default', '    raise HTTPError(req.full_url, code, msg, hdrs, fp)', 'E   urllib.error.HTTPError: HTTP Error 403: Forbidden']",,,115,,same
,,tests.test_place,Error,collection failure,"['    response = self.parent.error(', '/usr/local/lib/python3.10/urllib/request.py:563: in error', '/usr/local/lib/python3.10/urllib/request.py:643: in http_error_default', '    raise HTTPError(req.full_url, code, msg, hdrs, fp)', 'E   urllib.error.HTTPError: HTTP Error 403: Forbidden']",,,193,,same
,,tests.test_place,Error,collection failure,"['    response = self.parent.error(', '/usr/local/lib/python3.10/urllib/request.py:563: in error', '/usr/local/lib/python3.10/urllib/request.py:643: in http_error_default', '    raise HTTPError(req.full_url, code, msg, hdrs, fp)', 'E   urllib.error.HTTPError: HTTP Error 403: Forbidden']",,,69,,same
,,tests.test_place,Error,collection failure,"['    response = self.parent.error(', '/usr/local/lib/python3.10/urllib/request.py:563: in error', '/usr/local/lib/python3.10/urllib/request.py:643: in http_error_default', '    raise HTTPError(req.full_url, code, msg, hdrs, fp)', 'E   urllib.error.HTTPError: HTTP Error 403: Forbidden']",,,164,,same
,,tests.test_place,Error,collection failure,"['    response = self.parent.error(', '/usr/local/lib/python3.10/urllib/request.py:563: in error', '/usr/local/lib/python3.10/urllib/request.py:643: in http_error_default', '    raise HTTPError(req.full_url, code, msg, hdrs, fp)', 'E   urllib.error.HTTPError: HTTP Error 403: Forbidden']",,,33,,same
,,tests.test_place,Error,collection failure,"['    response = self.parent.error(', '/usr/local/lib/python3.10/urllib/request.py:563: in error', '/usr/local/lib/python3.10/urllib/request.py:643: in http_error_default', '    raise HTTPError(req.full_url, code, msg, hdrs, fp)', 'E   urllib.error.HTTPError: HTTP Error 403: Forbidden']",,,40,,same
,,tests.test_place,Error,collection failure,"['    response = self.parent.error(', '/usr/local/lib/python3.10/urllib/request.py:563: in error', '/usr/local/lib/python3.10/urllib/request.py:643: in http_error_default', '    raise HTTPError(req.full_url, code, msg, hdrs, fp)', 'E   urllib.error.HTTPError: HTTP Error 403: Forbidden']",,,18,,same
,,tests.test_place,Error,collection failure,"['    response = self.parent.error(', '/usr/local/lib/python3.10/urllib/request.py:563: in error', '/usr/local/lib/python3.10/urllib/request.py:643: in http_error_default', '    raise HTTPError(req.full_url, code, msg, hdrs, fp)', 'E   urllib.error.HTTPError: HTTP Error 403: Forbidden']",,,82,,same
,,tests.test_place,Error,collection failure,"['    response = self.parent.error(', '/usr/local/lib/python3.10/urllib/request.py:563: in error', '/usr/local/lib/python3.10/urllib/request.py:643: in http_error_default', '    raise HTTPError(req.full_url, code, msg, hdrs, fp)', 'E   urllib.error.HTTPError: HTTP Error 403: Forbidden']",,,56,,same
,,tests.test_place,Error,collection failure,"['    response = self.parent.error(', '/usr/local/lib/python3.10/urllib/request.py:563: in error', '/usr/local/lib/python3.10/urllib/request.py:643: in http_error_default', '    raise HTTPError(req.full_url, code, msg, hdrs, fp)', 'E   urllib.error.HTTPError: HTTP Error 403: Forbidden']",,,198,,same
,,tests.test_place,Error,collection failure,"['    response = self.parent.error(', '/usr/local/lib/python3.10/urllib/request.py:563: in error', '/usr/local/lib/python3.10/urllib/request.py:643: in http_error_default', '    raise HTTPError(req.full_url, code, msg, hdrs, fp)', 'E   urllib.error.HTTPError: HTTP Error 403: Forbidden']",,,199,,same
,,tests.test_place,Error,collection failure,"['    response = self.parent.error(', '/usr/local/lib/python3.10/urllib/request.py:563: in error', '/usr/local/lib/python3.10/urllib/request.py:643: in http_error_default', '    raise HTTPError(req.full_url, code, msg, hdrs, fp)', 'E   urllib.error.HTTPError: HTTP Error 403: Forbidden']",,,75,,same
,,tests.test_place,Error,collection failure,"['    response = self.parent.error(', '/usr/local/lib/python3.10/urllib/request.py:563: in error', '/usr/local/lib/python3.10/urllib/request.py:643: in http_error_default', '    raise HTTPError(req.full_url, code, msg, hdrs, fp)', 'E   urllib.error.HTTPError: HTTP Error 403: Forbidden']",,,192,,same
,,tests.test_place,Error,collection failure,"['    response = self.parent.error(', '/usr/local/lib/python3.10/urllib/request.py:563: in error', '/usr/local/lib/python3.10/urllib/request.py:643: in http_error_default', '    raise HTTPError(req.full_url, code, msg, hdrs, fp)', 'E   urllib.error.HTTPError: HTTP Error 403: Forbidden']",,,65,,same
,,tests.test_place,Error,collection failure,"['    response = self.parent.error(', '/usr/local/lib/python3.10/urllib/request.py:563: in error', '/usr/local/lib/python3.10/urllib/request.py:643: in http_error_default', '    raise HTTPError(req.full_url, code, msg, hdrs, fp)', 'E   urllib.error.HTTPError: HTTP Error 403: Forbidden']",,,37,,same
,,tests.test_place,Error,collection failure,"['    response = self.parent.error(', '/usr/local/lib/python3.10/urllib/request.py:563: in error', '/usr/local/lib/python3.10/urllib/request.py:643: in http_error_default', '    raise HTTPError(req.full_url, code, msg, hdrs, fp)', 'E   urllib.error.HTTPError: HTTP Error 403: Forbidden']",,,167,,same
,,tests.test_place,Error,collection failure,"['    response = self.parent.error(', '/usr/local/lib/python3.10/urllib/request.py:563: in error', '/usr/local/lib/python3.10/urllib/request.py:643: in http_error_default', '    raise HTTPError(req.full_url, code, msg, hdrs, fp)', 'E   urllib.error.HTTPError: HTTP Error 403: Forbidden']",,,42,,same
,,tests.test_place,Error,collection failure,"['    response = self.parent.error(', '/usr/local/lib/python3.10/urllib/request.py:563: in error', '/usr/local/lib/python3.10/urllib/request.py:643: in http_error_default', '    raise HTTPError(req.full_url, code, msg, hdrs, fp)', 'E   urllib.error.HTTPError: HTTP Error 403: Forbidden']",,,166,,same
,,tests.test_place,Error,collection failure,"['    response = self.parent.error(', '/usr/local/lib/python3.10/urllib/request.py:563: in error', '/usr/local/lib/python3.10/urllib/request.py:643: in http_error_default', '    raise HTTPError(req.full_url, code, msg, hdrs, fp)', 'E   urllib.error.HTTPError: HTTP Error 403: Forbidden']",,,48,,same
,,tests.test_place,Error,collection failure,"['    response = self.parent.error(', '/usr/local/lib/python3.10/urllib/request.py:563: in error', '/usr/local/lib/python3.10/urllib/request.py:643: in http_error_default', '    raise HTTPError(req.full_url, code, msg, hdrs, fp)', 'E   urllib.error.HTTPError: HTTP Error 403: Forbidden']",,,112,,same
,,tests.test_place,Error,collection failure,"['    response = self.parent.error(', '/usr/local/lib/python3.10/urllib/request.py:563: in error', '/usr/local/lib/python3.10/urllib/request.py:643: in http_error_default', '    raise HTTPError(req.full_url, code, msg, hdrs, fp)', 'E   urllib.error.HTTPError: HTTP Error 403: Forbidden']",,,171,,same
,,tests.test_place,Error,collection failure,"['    response = self.parent.error(', '/usr/local/lib/python3.10/urllib/request.py:563: in error', '/usr/local/lib/python3.10/urllib/request.py:643: in http_error_default', '    raise HTTPError(req.full_url, code, msg, hdrs, fp)', 'E   urllib.error.HTTPError: HTTP Error 403: Forbidden']",,,126,,same
,,tests.test_place,Error,collection failure,"['    response = self.parent.error(', '/usr/local/lib/python3.10/urllib/request.py:563: in error', '/usr/local/lib/python3.10/urllib/request.py:643: in http_error_default', '    raise HTTPError(req.full_url, code, msg, hdrs, fp)', 'E   urllib.error.HTTPError: HTTP Error 403: Forbidden']",,,72,,same
,,tests.test_place,Error,collection failure,"['    response = self.parent.error(', '/usr/local/lib/python3.10/urllib/request.py:563: in error', '/usr/local/lib/python3.10/urllib/request.py:643: in http_error_default', '    raise HTTPError(req.full_url, code, msg, hdrs, fp)', 'E   urllib.error.HTTPError: HTTP Error 403: Forbidden']",,,64,,same
,,tests.test_place,Error,collection failure,"['    response = self.parent.error(', '/usr/local/lib/python3.10/urllib/request.py:563: in error', '/usr/local/lib/python3.10/urllib/request.py:643: in http_error_default', '    raise HTTPError(req.full_url, code, msg, hdrs, fp)', 'E   urllib.error.HTTPError: HTTP Error 403: Forbidden']",,,113,,same
,,tests.test_place,Error,collection failure,"['    response = self.parent.error(', '/usr/local/lib/python3.10/urllib/request.py:563: in error', '/usr/local/lib/python3.10/urllib/request.py:643: in http_error_default', '    raise HTTPError(req.full_url, code, msg, hdrs, fp)', 'E   urllib.error.HTTPError: HTTP Error 403: Forbidden']",,,21,,same
,,tests.test_place,Error,collection failure,"['    response = self.parent.error(', '/usr/local/lib/python3.10/urllib/request.py:563: in error', '/usr/local/lib/python3.10/urllib/request.py:643: in http_error_default', '    raise HTTPError(req.full_url, code, msg, hdrs, fp)', 'E   urllib.error.HTTPError: HTTP Error 403: Forbidden']",,,168,,same
,,tests.test_place,Error,collection failure,"['    response = self.parent.error(', '/usr/local/lib/python3.10/urllib/request.py:563: in error', '/usr/local/lib/python3.10/urllib/request.py:643: in http_error_default', '    raise HTTPError(req.full_url, code, msg, hdrs, fp)', 'E   urllib.error.HTTPError: HTTP Error 403: Forbidden']",,,182,,same
,,tests.test_place,Error,collection failure,"['    response = self.parent.error(', '/usr/local/lib/python3.10/urllib/request.py:563: in error', '/usr/local/lib/python3.10/urllib/request.py:643: in http_error_default', '    raise HTTPError(req.full_url, code, msg, hdrs, fp)', 'E   urllib.error.HTTPError: HTTP Error 403: Forbidden']",,,60,,same
,,tests.test_place,Error,collection failure,"['    response = self.parent.error(', '/usr/local/lib/python3.10/urllib/request.py:563: in error', '/usr/local/lib/python3.10/urllib/request.py:643: in http_error_default', '    raise HTTPError(req.full_url, code, msg, hdrs, fp)', 'E   urllib.error.HTTPError: HTTP Error 403: Forbidden']",,,183,,same
,,tests.test_place,Error,collection failure,"['    response = self.parent.error(', '/usr/local/lib/python3.10/urllib/request.py:563: in error', '/usr/local/lib/python3.10/urllib/request.py:643: in http_error_default', '    raise HTTPError(req.full_url, code, msg, hdrs, fp)', 'E   urllib.error.HTTPError: HTTP Error 403: Forbidden']",,,24,,same
,,tests.test_place,Error,collection failure,"['    response = self.parent.error(', '/usr/local/lib/python3.10/urllib/request.py:563: in error', '/usr/local/lib/python3.10/urllib/request.py:643: in http_error_default', '    raise HTTPError(req.full_url, code, msg, hdrs, fp)', 'E   urllib.error.HTTPError: HTTP Error 403: Forbidden']",,,124,,same
,,tests.test_place,Error,collection failure,"['    response = self.parent.error(', '/usr/local/lib/python3.10/urllib/request.py:563: in error', '/usr/local/lib/python3.10/urllib/request.py:643: in http_error_default', '    raise HTTPError(req.full_url, code, msg, hdrs, fp)', 'E   urllib.error.HTTPError: HTTP Error 403: Forbidden']",,,187,,same
,,tests.test_place,Error,collection failure,"['    response = self.parent.error(', '/usr/local/lib/python3.10/urllib/request.py:563: in error', '/usr/local/lib/python3.10/urllib/request.py:643: in http_error_default', '    raise HTTPError(req.full_url, code, msg, hdrs, fp)', 'E   urllib.error.HTTPError: HTTP Error 403: Forbidden']",,,34,,same
,,tests.test_place,Error,collection failure,"['    response = self.parent.error(', '/usr/local/lib/python3.10/urllib/request.py:563: in error', '/usr/local/lib/python3.10/urllib/request.py:643: in http_error_default', '    raise HTTPError(req.full_url, code, msg, hdrs, fp)', 'E   urllib.error.HTTPError: HTTP Error 403: Forbidden']",,,132,,same
,,tests.test_place,Error,collection failure,"['    response = self.parent.error(', '/usr/local/lib/python3.10/urllib/request.py:563: in error', '/usr/local/lib/python3.10/urllib/request.py:643: in http_error_default', '    raise HTTPError(req.full_url, code, msg, hdrs, fp)', 'E   urllib.error.HTTPError: HTTP Error 403: Forbidden']",,,15,,same
,,tests.test_place,Error,collection failure,"['    response = self.parent.error(', '/usr/local/lib/python3.10/urllib/request.py:563: in error', '/usr/local/lib/python3.10/urllib/request.py:643: in http_error_default', '    raise HTTPError(req.full_url, code, msg, hdrs, fp)', 'E   urllib.error.HTTPError: HTTP Error 403: Forbidden']",,,123,,same
,,tests.test_place,Error,collection failure,"['    response = self.parent.error(', '/usr/local/lib/python3.10/urllib/request.py:563: in error', '/usr/local/lib/python3.10/urllib/request.py:643: in http_error_default', '    raise HTTPError(req.full_url, code, msg, hdrs, fp)', 'E   urllib.error.HTTPError: HTTP Error 403: Forbidden']",,,85,,same
,,tests.test_place,Error,collection failure,"['    response = self.parent.error(', '/usr/local/lib/python3.10/urllib/request.py:563: in error', '/usr/local/lib/python3.10/urllib/request.py:643: in http_error_default', '    raise HTTPError(req.full_url, code, msg, hdrs, fp)', 'E   urllib.error.HTTPError: HTTP Error 403: Forbidden']",,,152,,same
,,tests.test_place,Error,collection failure,"['    response = self.parent.error(', '/usr/local/lib/python3.10/urllib/request.py:563: in error', '/usr/local/lib/python3.10/urllib/request.py:643: in http_error_default', '    raise HTTPError(req.full_url, code, msg, hdrs, fp)', 'E   urllib.error.HTTPError: HTTP Error 403: Forbidden']",,,39,,same
,,tests.test_place,Error,collection failure,"['    response = self.parent.error(', '/usr/local/lib/python3.10/urllib/request.py:563: in error', '/usr/local/lib/python3.10/urllib/request.py:643: in http_error_default', '    raise HTTPError(req.full_url, code, msg, hdrs, fp)', 'E   urllib.error.HTTPError: HTTP Error 403: Forbidden']",,,106,,same
,,tests.test_place,Error,collection failure,"['    response = self.parent.error(', '/usr/local/lib/python3.10/urllib/request.py:563: in error', '/usr/local/lib/python3.10/urllib/request.py:643: in http_error_default', '    raise HTTPError(req.full_url, code, msg, hdrs, fp)', 'E   urllib.error.HTTPError: HTTP Error 403: Forbidden']",,,186,,same
,,tests.test_place,Error,collection failure,"['    response = self.parent.error(', '/usr/local/lib/python3.10/urllib/request.py:563: in error', '/usr/local/lib/python3.10/urllib/request.py:643: in http_error_default', '    raise HTTPError(req.full_url, code, msg, hdrs, fp)', 'E   urllib.error.HTTPError: HTTP Error 403: Forbidden']",,,150,,same
,,tests.test_place,Error,collection failure,"['    response = self.parent.error(', '/usr/local/lib/python3.10/urllib/request.py:563: in error', '/usr/local/lib/python3.10/urllib/request.py:643: in http_error_default', '    raise HTTPError(req.full_url, code, msg, hdrs, fp)', 'E   urllib.error.HTTPError: HTTP Error 403: Forbidden']",,,91,,same
,,tests.test_place,Error,collection failure,"['    response = self.parent.error(', '/usr/local/lib/python3.10/urllib/request.py:563: in error', '/usr/local/lib/python3.10/urllib/request.py:643: in http_error_default', '    raise HTTPError(req.full_url, code, msg, hdrs, fp)', 'E   urllib.error.HTTPError: HTTP Error 403: Forbidden']",,,194,,same
,,tests.test_place,Error,collection failure,"['    response = self.parent.error(', '/usr/local/lib/python3.10/urllib/request.py:563: in error', '/usr/local/lib/python3.10/urllib/request.py:643: in http_error_default', '    raise HTTPError(req.full_url, code, msg, hdrs, fp)', 'E   urllib.error.HTTPError: HTTP Error 403: Forbidden']",,,1,,same
,,tests.test_place,Error,collection failure,"['    response = self.parent.error(', '/usr/local/lib/python3.10/urllib/request.py:563: in error', '/usr/local/lib/python3.10/urllib/request.py:643: in http_error_default', '    raise HTTPError(req.full_url, code, msg, hdrs, fp)', 'E   urllib.error.HTTPError: HTTP Error 403: Forbidden']",,,6,,same
,,tests.test_place,Error,collection failure,"['    response = self.parent.error(', '/usr/local/lib/python3.10/urllib/request.py:563: in error', '/usr/local/lib/python3.10/urllib/request.py:643: in http_error_default', '    raise HTTPError(req.full_url, code, msg, hdrs, fp)', 'E   urllib.error.HTTPError: HTTP Error 403: Forbidden']",,,158,,same
,,tests.test_place,Error,collection failure,"['    response = self.parent.error(', '/usr/local/lib/python3.10/urllib/request.py:563: in error', '/usr/local/lib/python3.10/urllib/request.py:643: in http_error_default', '    raise HTTPError(req.full_url, code, msg, hdrs, fp)', 'E   urllib.error.HTTPError: HTTP Error 403: Forbidden']",,,169,,same
,,tests.test_place,Error,collection failure,"['    response = self.parent.error(', '/usr/local/lib/python3.10/urllib/request.py:563: in error', '/usr/local/lib/python3.10/urllib/request.py:643: in http_error_default', '    raise HTTPError(req.full_url, code, msg, hdrs, fp)', 'E   urllib.error.HTTPError: HTTP Error 403: Forbidden']",,,143,,same
,,tests.test_place,Error,collection failure,"['    response = self.parent.error(', '/usr/local/lib/python3.10/urllib/request.py:563: in error', '/usr/local/lib/python3.10/urllib/request.py:643: in http_error_default', '    raise HTTPError(req.full_url, code, msg, hdrs, fp)', 'E   urllib.error.HTTPError: HTTP Error 403: Forbidden']",,,88,,same
,,tests.test_observations,Error,collection failure,"['E   TimeoutError: [Errno 110] Connection timed out', 'During handling of the above exception, another exception occurred:', ""E   urllib.error.URLError: <urlopen error ftp error: TimeoutError(110, 'Connection timed out')>""]",,,157,,same
,,tests.test_place,Error,collection failure,"['    response = self.parent.error(', '/usr/local/lib/python3.10/urllib/request.py:563: in error', '/usr/local/lib/python3.10/urllib/request.py:643: in http_error_default', '    raise HTTPError(req.full_url, code, msg, hdrs, fp)', 'E   urllib.error.HTTPError: HTTP Error 403: Forbidden']",,,157,,same
,,tests.test_place,Error,collection failure,"['    response = self.parent.error(', '/usr/local/lib/python3.10/urllib/request.py:563: in error', '/usr/local/lib/python3.10/urllib/request.py:643: in http_error_default', '    raise HTTPError(req.full_url, code, msg, hdrs, fp)', 'E   urllib.error.HTTPError: HTTP Error 403: Forbidden']",,,161,,same
,,tests.test_place,Error,collection failure,"['    response = self.parent.error(', '/usr/local/lib/python3.10/urllib/request.py:563: in error', '/usr/local/lib/python3.10/urllib/request.py:643: in http_error_default', '    raise HTTPError(req.full_url, code, msg, hdrs, fp)', 'E   urllib.error.HTTPError: HTTP Error 403: Forbidden']",,,26,,same
,,tests.test_place,Error,collection failure,"['    response = self.parent.error(', '/usr/local/lib/python3.10/urllib/request.py:563: in error', '/usr/local/lib/python3.10/urllib/request.py:643: in http_error_default', '    raise HTTPError(req.full_url, code, msg, hdrs, fp)', 'E   urllib.error.HTTPError: HTTP Error 403: Forbidden']",,,36,,same
,,tests.test_place,Error,collection failure,"['    response = self.parent.error(', '/usr/local/lib/python3.10/urllib/request.py:563: in error', '/usr/local/lib/python3.10/urllib/request.py:643: in http_error_default', '    raise HTTPError(req.full_url, code, msg, hdrs, fp)', 'E   urllib.error.HTTPError: HTTP Error 403: Forbidden']",,,185,,same
,,tests.test_place,Error,collection failure,"['    response = self.parent.error(', '/usr/local/lib/python3.10/urllib/request.py:563: in error', '/usr/local/lib/python3.10/urllib/request.py:643: in http_error_default', '    raise HTTPError(req.full_url, code, msg, hdrs, fp)', 'E   urllib.error.HTTPError: HTTP Error 403: Forbidden']",,,74,,same
,,tests.test_place,Error,collection failure,"['    response = self.parent.error(', '/usr/local/lib/python3.10/urllib/request.py:563: in error', '/usr/local/lib/python3.10/urllib/request.py:643: in http_error_default', '    raise HTTPError(req.full_url, code, msg, hdrs, fp)', 'E   urllib.error.HTTPError: HTTP Error 403: Forbidden']",,,130,,same
,,tests.test_place,Error,collection failure,"['    response = self.parent.error(', '/usr/local/lib/python3.10/urllib/request.py:563: in error', '/usr/local/lib/python3.10/urllib/request.py:643: in http_error_default', '    raise HTTPError(req.full_url, code, msg, hdrs, fp)', 'E   urllib.error.HTTPError: HTTP Error 403: Forbidden']",,,99,,same
,,tests.test_place,Error,collection failure,"['    response = self.parent.error(', '/usr/local/lib/python3.10/urllib/request.py:563: in error', '/usr/local/lib/python3.10/urllib/request.py:643: in http_error_default', '    raise HTTPError(req.full_url, code, msg, hdrs, fp)', 'E   urllib.error.HTTPError: HTTP Error 403: Forbidden']",,,114,,same
,,tests.test_place,Error,collection failure,"['    response = self.parent.error(', '/usr/local/lib/python3.10/urllib/request.py:563: in error', '/usr/local/lib/python3.10/urllib/request.py:643: in http_error_default', '    raise HTTPError(req.full_url, code, msg, hdrs, fp)', 'E   urllib.error.HTTPError: HTTP Error 403: Forbidden']",,,90,,same
,,tests.test_place,Error,collection failure,"['    response = self.parent.error(', '/usr/local/lib/python3.10/urllib/request.py:563: in error', '/usr/local/lib/python3.10/urllib/request.py:643: in http_error_default', '    raise HTTPError(req.full_url, code, msg, hdrs, fp)', 'E   urllib.error.HTTPError: HTTP Error 403: Forbidden']",,,159,,same
,,tests.test_place,Error,collection failure,"['    response = self.parent.error(', '/usr/local/lib/python3.10/urllib/request.py:563: in error', '/usr/local/lib/python3.10/urllib/request.py:643: in http_error_default', '    raise HTTPError(req.full_url, code, msg, hdrs, fp)', 'E   urllib.error.HTTPError: HTTP Error 403: Forbidden']",,,119,,same
,,tests.test_place,Error,collection failure,"['    response = self.parent.error(', '/usr/local/lib/python3.10/urllib/request.py:563: in error', '/usr/local/lib/python3.10/urllib/request.py:643: in http_error_default', '    raise HTTPError(req.full_url, code, msg, hdrs, fp)', 'E   urllib.error.HTTPError: HTTP Error 403: Forbidden']",,,138,,same
,,tests.test_place,Error,collection failure,"['    response = self.parent.error(', '/usr/local/lib/python3.10/urllib/request.py:563: in error', '/usr/local/lib/python3.10/urllib/request.py:643: in http_error_default', '    raise HTTPError(req.full_url, code, msg, hdrs, fp)', 'E   urllib.error.HTTPError: HTTP Error 403: Forbidden']",,,70,,same
,,tests.test_place,Error,collection failure,"['    response = self.parent.error(', '/usr/local/lib/python3.10/urllib/request.py:563: in error', '/usr/local/lib/python3.10/urllib/request.py:643: in http_error_default', '    raise HTTPError(req.full_url, code, msg, hdrs, fp)', 'E   urllib.error.HTTPError: HTTP Error 403: Forbidden']",,,196,,same
,,tests.test_place,Error,collection failure,"['    response = self.parent.error(', '/usr/local/lib/python3.10/urllib/request.py:563: in error', '/usr/local/lib/python3.10/urllib/request.py:643: in http_error_default', '    raise HTTPError(req.full_url, code, msg, hdrs, fp)', 'E   urllib.error.HTTPError: HTTP Error 403: Forbidden']",,,89,,same
,,tests.test_place,Error,collection failure,"['    response = self.parent.error(', '/usr/local/lib/python3.10/urllib/request.py:563: in error', '/usr/local/lib/python3.10/urllib/request.py:643: in http_error_default', '    raise HTTPError(req.full_url, code, msg, hdrs, fp)', 'E   urllib.error.HTTPError: HTTP Error 403: Forbidden']",,,197,,same
,,tests.test_place,Error,collection failure,"['    response = self.parent.error(', '/usr/local/lib/python3.10/urllib/request.py:563: in error', '/usr/local/lib/python3.10/urllib/request.py:643: in http_error_default', '    raise HTTPError(req.full_url, code, msg, hdrs, fp)', 'E   urllib.error.HTTPError: HTTP Error 403: Forbidden']",,,30,,same
,,tests.test_place,Error,collection failure,"['    response = self.parent.error(', '/usr/local/lib/python3.10/urllib/request.py:563: in error', '/usr/local/lib/python3.10/urllib/request.py:643: in http_error_default', '    raise HTTPError(req.full_url, code, msg, hdrs, fp)', 'E   urllib.error.HTTPError: HTTP Error 403: Forbidden']",,,46,,same
,,tests.test_place,Error,collection failure,"['    response = self.parent.error(', '/usr/local/lib/python3.10/urllib/request.py:563: in error', '/usr/local/lib/python3.10/urllib/request.py:643: in http_error_default', '    raise HTTPError(req.full_url, code, msg, hdrs, fp)', 'E   urllib.error.HTTPError: HTTP Error 403: Forbidden']",,,137,,same
